"""
Search strategies for parameter optimization. Task 5.3 (M3).

SearchStrategy implemented exactly per architecture_overview.md §5.7
-- not redefined. suggest()'s type hint there is `-> dict`, but a
sentinel is still needed to signal "search exhausted"; None is used
for that (a very standard Python idiom -- next(iterator, None),
dict.get(), etc. -- and Python doesn't enforce return-type hints at
runtime, so this isn't a redefinition of the interface, just a choice
of what concrete subclasses return). An empty dict was considered and
rejected as the sentinel: strategy_params_grid can legitimately
contain an empty params dict for a zero-argument strategy, which
would be ambiguous with "exhausted".
"""

from __future__ import annotations

import itertools
from abc import ABC, abstractmethod
from typing import Optional

from src.exceptions import ConfigurationError


class SearchStrategy(ABC):
    @abstractmethod
    def suggest(self) -> Optional[dict]:
        """Return the next {"grid_step", "profit_target", "strategy_params"}
        combination to evaluate, or None once the search is exhausted."""
        ...

    @abstractmethod
    def report(self, params: dict, result) -> None:
        """Feed a completed evaluation's result (a SimulationResult, or
        None if the combination failed -- Task 4.4) back to the search
        strategy."""
        ...


class GridSearch(SearchStrategy):
    """Wraps the existing itertools.product exhaustive sweep behind the
    SearchStrategy interface. Default/fallback strategy -- reproduces
    today's sweep behavior exactly: same combinations, same order,
    literally generated by itertools.product internally, not a
    reimplementation that merely intends to match it."""

    def __init__(self, grid_steps, profit_targets, strategy_params_grid):
        self._combinations = itertools.product(grid_steps, profit_targets, strategy_params_grid)

    def suggest(self) -> Optional[dict]:
        try:
            grid_step, profit_target, strategy_params = next(self._combinations)
        except StopIteration:
            return None
        return {"grid_step": grid_step, "profit_target": profit_target, "strategy_params": strategy_params}

    def report(self, params: dict, result) -> None:
        pass  # exhaustive search never adapts based on feedback


class BayesianSearch(SearchStrategy):
    """Optuna-backed search over the same discrete space GridSearch
    enumerates exhaustively -- every grid_step/profit_target/
    strategy_params entry is a categorical choice, not a continuous
    range, since the caller already specified the exact discrete
    candidates it wants considered (matching how run_sweep has always
    taken explicit lists, not bounds).

    Search objective contract: the objective is result.metrics[rank_by]
    -- the same Task 4.7 ranking metric run_sweep itself sorts by --
    with an explicit maximize/minimize direction (defaults to
    "maximize", matching run_sweep's own default descending sort).
    Ties are Optuna's own TPESampler's concern, made deterministic by
    the required seed.

    Uses Optuna's ask/tell interface (study.ask() / study.tell())
    rather than optuna.study.optimize(objective_fn) specifically so
    suggest()/report() can stay a clean two-method pull-based
    interface -- optimize() expects to own the whole evaluation loop
    itself, which conflicts with SearchStrategy's contract of being
    called externally, one suggestion at a time (or one batch at a
    time -- see run_sweep's own batching for n_jobs > 1).
    """

    def __init__(
        self,
        grid_steps,
        profit_targets,
        strategy_params_grid,
        rank_by: str = "Capital Velocity Index",
        direction: str = "maximize",
        n_trials: Optional[int] = None,
        seed: Optional[int] = None,
    ):
        try:
            import optuna
        except ImportError as e:
            raise ConfigurationError(
                "BayesianSearch requires the 'optuna' package, which is not installed. "
                "Install it (pip install optuna) or use search_strategy='grid' instead."
            ) from e

        if direction not in ("maximize", "minimize"):
            raise ConfigurationError(f"direction must be 'maximize' or 'minimize', got {direction!r}")

        optuna.logging.set_verbosity(optuna.logging.WARNING)

        self._grid_steps = list(grid_steps)
        self._profit_targets = list(profit_targets)
        self._strategy_params_grid = list(strategy_params_grid)
        self.rank_by = rank_by
        total_combinations = len(self._grid_steps) * len(self._profit_targets) * len(self._strategy_params_grid)
        self.n_trials = n_trials if n_trials is not None else total_combinations

        sampler = optuna.samplers.TPESampler(seed=seed)
        self._study = optuna.create_study(direction=direction, sampler=sampler)
        self._trial_count = 0
        self._pending_trials: dict[int, "optuna.trial.Trial"] = {}

    def suggest(self) -> Optional[dict]:
        if self._trial_count >= self.n_trials:
            return None
        trial = self._study.ask()
        grid_step = trial.suggest_categorical("grid_step", self._grid_steps)
        profit_target = trial.suggest_categorical("profit_target", self._profit_targets)
        params_index = trial.suggest_categorical("strategy_params_index", list(range(len(self._strategy_params_grid))))
        self._trial_count += 1
        self._pending_trials[trial.number] = trial
        return {
            "grid_step": grid_step,
            "profit_target": profit_target,
            "strategy_params": self._strategy_params_grid[params_index],
            "_trial_number": trial.number,  # internal bookkeeping, ignored by run_sweep when running the combination
        }

    def report(self, params: dict, result) -> None:
        import optuna

        trial_number = params["_trial_number"]
        trial = self._pending_trials.pop(trial_number)
        if result is None or "error" in getattr(result, "metrics", {}):
            self._study.tell(trial, state=optuna.trial.TrialState.FAIL)
            return
        objective_value = result.metrics.get(self.rank_by)
        if objective_value is None:
            self._study.tell(trial, state=optuna.trial.TrialState.FAIL)
            return
        self._study.tell(trial, objective_value)
