"""
Search strategies for parameter optimization. Task 5.3 (M3).

SearchStrategy implemented exactly per architecture_overview.md §5.7
-- not redefined. suggest()'s type hint there is `-> dict`, but a
sentinel is still needed to signal "search exhausted"; None is used
for that (a very standard Python idiom -- next(iterator, None),
dict.get(), etc. -- and Python doesn't enforce return-type hints at
runtime, so this isn't a redefinition of the interface, just a choice
of what concrete subclasses return). An empty dict was considered and
rejected as the sentinel: strategy_params_grid can legitimately
contain an empty params dict for a zero-argument strategy, which
would be ambiguous with "exhausted".
"""

from __future__ import annotations

import itertools
from abc import ABC, abstractmethod

from src.exceptions import ConfigurationError


class SearchStrategy(ABC):
    """Pull-based interface for proposing parameter combinations.

    The caller drives the loop: it asks for a combination, evaluates it,
    and reports the result back. That inversion (rather than handing an
    objective function to the strategy) is what lets run_sweep own
    parallelism, error isolation, and result collection uniformly across
    exhaustive and adaptive searches alike.
    """

    @abstractmethod
    def suggest(self) -> dict | None:
        """Return the next {"grid_step", "profit_target", "strategy_params"}
        combination to evaluate, or None once the search is exhausted."""
        ...

    @abstractmethod
    def report(self, params: dict, result) -> None:
        """Feed a completed evaluation's result (a SimulationResult, or
        None if the combination failed -- Task 4.4) back to the search
        strategy."""
        ...


class GridSearch(SearchStrategy):
    """Wraps the existing itertools.product exhaustive sweep behind the
    SearchStrategy interface. Default/fallback strategy -- reproduces
    today's sweep behavior exactly: same combinations, same order,
    literally generated by itertools.product internally, not a
    reimplementation that merely intends to match it."""

    def __init__(self, grid_steps, profit_targets, strategy_params_grid):
        """Build the exhaustive product of the three axes, lazily.

        itertools.product is consumed as an iterator rather than
        materialized, so a large space costs nothing until it is walked.
        """
        self._combinations = itertools.product(grid_steps, profit_targets, strategy_params_grid)

    def suggest(self) -> dict | None:
        """Next combination in itertools.product order, or None when the
        space is exhausted."""
        try:
            grid_step, profit_target, strategy_params = next(self._combinations)
        except StopIteration:
            return None
        return {
            "grid_step": grid_step,
            "profit_target": profit_target,
            "strategy_params": strategy_params,
        }

    def report(self, params: dict, result) -> None:
        """No-op: an exhaustive search visits every combination
        regardless of outcome, so feedback cannot change what it does.

        This being a genuine no-op is also what makes GridSearch
        deterministic under parallelism -- batch boundaries cannot
        affect which combinations are produced.
        """
        pass


def decompose_params_grid(strategy_params_grid: list[dict]) -> dict[str, list] | None:
    """Recover per-key candidate lists from an expanded params grid, or
    None if that cannot be done safely.

    WHY THIS EXISTS. BayesianSearch originally encoded the whole
    strategy_params dict as ONE categorical index over the expanded
    grid. Optuna's TPE sampler therefore saw N opaque numbered buckets
    with no structure -- it could not learn "high confidence_k is bad"
    independently of "which horizon_days", because as far as it knew
    bucket 4102 and bucket 4103 were unrelated labels.

    The practical effect was measured: a 100-trial search over an
    8,640-combination strategy space produced 100 distinct combinations
    and zero repeats, with no convergence on any strategy parameter --
    while grid_step and profit_target, which WERE separate categorical
    axes, converged hard within ~40 trials. Same sampler, same run; the
    only difference was the encoding.

    Decomposing is only valid when the grid is exactly the cartesian
    product of its per-key values. src/config.py's
    expand_strategy_params produces exactly that, so the common path
    qualifies -- but run_sweep also accepts an arbitrary hand-written
    list of dicts, and suggesting per-key would then invent
    combinations the caller never asked for. Hence the checks below and
    the None fallback, rather than assuming.

    Returns {key: [values...]} preserving first-seen value order (so a
    seeded search stays reproducible), or None when any of these hold:
      - the grid is empty
      - the dicts do not all share the same keys
      - a value is unhashable (can't be a categorical choice)
      - the grid is not the full cartesian product (size mismatch)
      - the grid contains duplicate combinations
    """
    if not strategy_params_grid:
        return None

    keys = set(strategy_params_grid[0])
    if any(set(d) != keys for d in strategy_params_grid):
        return None

    per_key: dict[str, list] = {}
    try:
        for key in sorted(keys):
            # dict.fromkeys dedups while preserving first-seen order.
            per_key[key] = list(dict.fromkeys(d[key] for d in strategy_params_grid))
    except TypeError:
        # An unhashable value (a list, say) cannot be a categorical.
        return None

    expected = 1
    for values in per_key.values():
        expected *= len(values)
    if expected != len(strategy_params_grid):
        return None

    seen = set()
    for d in strategy_params_grid:
        signature = tuple(sorted(d.items()))
        if signature in seen:
            return None
        seen.add(signature)

    return per_key


class BayesianSearch(SearchStrategy):
    """Optuna-backed search over the same discrete space GridSearch
    enumerates exhaustively -- every grid_step/profit_target/
    strategy_params entry is a categorical choice, not a continuous
    range, since the caller already specified the exact discrete
    candidates it wants considered (matching how run_sweep has always
    taken explicit lists, not bounds).

    Search objective contract: the objective is result.metrics[rank_by]
    -- the same Task 4.7 ranking metric run_sweep itself sorts by --
    with an explicit maximize/minimize direction (defaults to
    "maximize", matching run_sweep's own default descending sort).
    Ties are Optuna's own TPESampler's concern, made deterministic by
    the required seed.

    Uses Optuna's ask/tell interface (study.ask() / study.tell())
    rather than optuna.study.optimize(objective_fn) specifically so
    suggest()/report() can stay a clean two-method pull-based
    interface -- optimize() expects to own the whole evaluation loop
    itself, which conflicts with SearchStrategy's contract of being
    called externally, one suggestion at a time (or one batch at a
    time -- see run_sweep's own batching for n_jobs > 1).
    """

    def __init__(
        self,
        grid_steps,
        profit_targets,
        strategy_params_grid,
        rank_by: str = "Capital Velocity Index",
        direction: str = "maximize",
        n_trials: int | None = None,
        seed: int | None = None,
    ):
        """Configure an Optuna study over the same discrete space.

        n_trials defaults to the FULL combination count, so an
        unconfigured BayesianSearch explores as much as grid search
        would; pass a smaller budget to actually save evaluations. seed
        makes the search reproducible.

        Raises ConfigurationError at construction if optuna is missing,
        rather than failing later inside suggest() or silently degrading
        to grid search.
        """
        try:
            import optuna
        except ImportError as e:
            raise ConfigurationError(
                "BayesianSearch requires the 'optuna' package, which is not installed. "
                "Install it (pip install optuna) or use search_strategy='grid' instead."
            ) from e

        if direction not in ("maximize", "minimize"):
            raise ConfigurationError(
                f"direction must be 'maximize' or 'minimize', got {direction!r}"
            )

        optuna.logging.set_verbosity(optuna.logging.WARNING)

        self._grid_steps = list(grid_steps)
        self._profit_targets = list(profit_targets)
        self._strategy_params_grid = list(strategy_params_grid)
        self.rank_by = rank_by
        total_combinations = (
            len(self._grid_steps) * len(self._profit_targets) * len(self._strategy_params_grid)
        )
        self.n_trials = n_trials if n_trials is not None else total_combinations

        # Per-key axes when the grid is a true cartesian product, so TPE
        # can learn each strategy parameter independently instead of
        # treating the whole dict as one opaque label. See
        # decompose_params_grid for why this matters and when it is
        # unsafe; None means fall back to the index encoding.
        axes = decompose_params_grid(self._strategy_params_grid)
        if axes is None:
            self._param_axes = None
            self._constant_params: dict = {}
        else:
            # A single-valued key is a constant, not a search dimension.
            # Handing it to suggest_categorical would add a useless axis
            # for TPE to model, so it is applied directly instead.
            self._param_axes = {k: v for k, v in axes.items() if len(v) > 1}
            self._constant_params = {k: v[0] for k, v in axes.items() if len(v) == 1}

        sampler = optuna.samplers.TPESampler(seed=seed)
        self._study = optuna.create_study(direction=direction, sampler=sampler)
        self._trial_count = 0
        self._pending_trials: dict[int, optuna.trial.Trial] = {}

    @property
    def decomposed(self) -> bool:
        """Whether strategy params are being searched per-key.

        Exposed because the difference is invisible in results but
        decisive for whether a search can converge at all -- a caller
        that expected per-key search and silently got the index
        fallback would just see a search that never narrows.
        """
        return self._param_axes is not None

    @property
    def search_axis_names(self) -> list[str]:
        """Strategy-param keys TPE is actually varying (constants
        excluded). Empty when running on the index fallback."""
        return sorted(self._param_axes) if self._param_axes else []

    def suggest(self) -> dict | None:
        """Ask Optuna for the next combination, or None once the trial
        budget is spent.

        Uses ask/tell rather than study.optimize() so the caller keeps
        control of the evaluation loop. The returned dict carries an
        internal _trial_number that report() needs; run_sweep ignores it.
        """
        if self._trial_count >= self.n_trials:
            return None
        trial = self._study.ask()
        grid_step = trial.suggest_categorical("grid_step", self._grid_steps)
        profit_target = trial.suggest_categorical("profit_target", self._profit_targets)

        if self._param_axes is not None:
            # One named categorical per strategy parameter. Prefixed so
            # a strategy param called "grid_step" could never collide
            # with the sweep axis of the same name.
            strategy_params = dict(self._constant_params)
            for key, values in self._param_axes.items():
                strategy_params[key] = trial.suggest_categorical(f"param_{key}", values)
        else:
            params_index = trial.suggest_categorical(
                "strategy_params_index", list(range(len(self._strategy_params_grid)))
            )
            strategy_params = self._strategy_params_grid[params_index]

        self._trial_count += 1
        self._pending_trials[trial.number] = trial
        return {
            "grid_step": grid_step,
            "profit_target": profit_target,
            "strategy_params": strategy_params,
            "_trial_number": trial.number,  # internal bookkeeping, ignored by run_sweep when running the combination
        }

    def report(self, params: dict, result) -> None:
        """Feed one evaluation back to Optuna.

        A failed combination (result is None, or metrics carry an error,
        or the ranking metric is absent) is told to Optuna as a FAILED
        trial rather than as a bad score -- scoring it would teach the
        sampler that a whole region is unpromising when in fact it was
        never measured.
        """
        import optuna

        trial_number = params["_trial_number"]
        trial = self._pending_trials.pop(trial_number)
        if result is None or "error" in getattr(result, "metrics", {}):
            self._study.tell(trial, state=optuna.trial.TrialState.FAIL)
            return
        objective_value = result.metrics.get(self.rank_by)
        if objective_value is None:
            self._study.tell(trial, state=optuna.trial.TrialState.FAIL)
            return
        self._study.tell(trial, objective_value)
